### ISSUE TITLE
Define an evaluation method for the AMS team

### ISSUE THREAD

**Issue by StefanDziwok** [AppSecure-nrw/security-belts#43]
Inititial Questions to ams in German:

IEM defines a surveymonkey survey that may be reused by other teams as well. The link is placed on our github page at the readme.md but also at all activity pages, the results are private.

Die TN der Umfrage müssen mit uns Kontakt aufnehmen können. --> Github-Ticket aufmachen
Wir wollen gerne mit den TN Kontakt aufnehmen. TN sollen die Möglichkeiten haben ihre Mailadresse anzugeben.

Können wir in SurveyMonkey nachträglich Änderungen machen?
Brauchen wir eine Versionierung der Umfrage?
Wir müssen wissen welche Security-Belt-Version wir abfragen (einfach so den git-hash mitgeben, oder timestamp).

## Allgemein
1. Wieso habt ihr euch für die Security Belts entschieden?
2. Entsteht durch die Belts eine Vergleichbarkeit von Teams? Falls ja: Ist das für euch relevant und gewollt?
3. Welcher Gürtel erscheint euch für euer Produkt sinnvoll und notwendig?
4. Habt oder braucht ihr außerhalb des Teams eine treibende Kraft? 
5. Wie organisiert ihr den Fortschritt eines Gürtels (z.b. Github Tickets)?
6. Wie verteilt ihr die Arbeit an den Belts im Team?
7. Gibt es außerhalb des Teams Stakeholder, die einen Reifegrad einfordern bzw. Erwartungen an eure Security-Kompetenz haben?

## Methodik (Readme.md)
1. Welche Texte habt ihr gelesen? (Überschriften zur Auswahl stellen)
2. Waren die Texte verständlich?
3. Waren die Texte hilfreich?
4. Welche Informationen fehlen euch?
5. Ist ein Quartal je Gürtel für euch realistisch?
6. Ist es gut, dass die Aktivitäten je Gürtel fest vorgeben sind oder wollt ihr mehr Freiheiten?

## Pro Aktivität 

(2x durchführen: direkt nach der Durchführung und ein paar Monate später)

1. Wie viele Stunden habt ihr gebraucht? 
2. Welche Texte habt ihr gelesen? (Überschriften zur Auswahl stellen)
3. Waren die Texte verständlich?
4. Waren die Texte hilfreich?
5. Welche Informationen fehlen euch?
6. Ist die Aktivität in diesem Gürtel passend? Oder kommt sie zu früh oder zu spät?
7. Wie viele Schwachstellen wurden durch die Aktivität gefunden?
8. Wie viele Schwachstellen wurden nicht von der Aktivität gefunden, sondern erst später durch einen Pen-Test?
9. Wie ist der Nutzen konkret für euer Team? (Skala von sehr niedrig bis sehr hoch)
10. Gibt es diese Aktivität bereits in eurem Team?

**Comment by StefanDziwok** [comment]
I need a review for the following survey:
https://www.surveymonkey.de/r/Z5RSM3D

**Comment by merschs** [comment]
Concerning the german version: as the whole security belts are in english, I think it would be enough to have the survey in english. Maybe we can highlicht the remark about free text field languages in german/english?

Review: I split this in two parts, the first parts contains general questions that question the questions/survey. The second part is about improving the current survey.

**Questions**
- Q10: What do we want to achieve with this question? In the current form nobody can answer this, we should at least give an alternative. 
- Q12: Do we need this question? I think we can get rid of it, as we do not want a list on possible ways to keep track. Maybe just replace it with "Do you keep track of your current belt progress?"

**Improvements** 
- Q2: develops -> develop
- Q2: Are all answers feature complete or do we need an "Other" field?
- Q10: What is your opinion? -> Do you think this is a good idea?
- Q13: No, we are faster. + No, we are slower. (hard to wrap your head around "too short/long")
- Q16: Extend the question to give a cause for the need? In order to achieve the security belts? / progress faster?
- Q16: Make the question mandatory
- Q17: "Are there stakeholders outside the team that require/demand a certain level of your software security?" ->  "Are there stakeholders, which are not part of your team, that require/demand a certain level of security for your software development process?" 
- Q21: common -> general
- Answers spanning from absolutely yes to absolutely no (Q10+Q14): can we have a slider (or one row presentation) ranging from those positions? (i.e. one side yes, the other no, and two in between positions, would make understandability much easier + added I don't know/care position on the side)

**Comment by StefanDziwok** [comment]
`Q10: What do we want to achieve with this question? In the current form nobody can answer this, we should at least give an alternative.`
I move this in the single belt survey.

`Q12: Do we need this question? I think we can get rid of it, as we do not want a list on possible ways to keep track. Maybe just replace it with "Do you keep track of your current belt progress?"`
I move this new question in the single belt survey.

**Comment by StefanDziwok** [comment]
`Q10: What is your opinion? -> Do you think this is a good idea?`
This would be too suggestive. I wanted to state an open question.

`Answers spanning from absolutely yes to absolutely no (Q10+Q14): can we have a slider (or one row presentation) ranging from those positions? (i.e. one side yes, the other no, and two in between positions, would make understandability much easier + added I don't know/care position on the side)`
If we use a slider, than no other inputs are possible for this question. Let's talk about this in a meeting.

**Comment by StefanDziwok** [comment]
I made a second survey, but not for a single activity but for a single belt. In my opinion, we need this but the single activity survey could be optional. What is our opinion?

Test-Link for the single belt survey.
https://www.surveymonkey.de/r/QYMVK5V

**Comment by StefanDziwok** [comment]
Feature Request: Enter a freely chosen pseudonym to be able to combine several questionnaires.

**Comment by StefanDziwok** [comment]
@merschs @bob5ec This is my update of the survey concerning the security belts' concept. In my opinion, this is the final version. I would appreciate your feedback.
https://www.surveymonkey.de/r/Z5RSM3D

**Comment by StefanDziwok** [comment]
@merschs I have incorporated all your comments into the second survey concerning a single belt.
https://www.surveymonkey.de/r/QYMVK5V
[2021-04-01_SurveyMonkey_SingleBelt.pdf](https://github.com/AppSecure-nrw/security-belts/files/6244922/2021-04-01_SurveyMonkey_SingleBelt.pdf)

**Comment by StefanDziwok** [comment]
Do we maybe need a third survey for feedback on a single activity as teams need several months for a belt? This would make the single belt survey shorter but in my opinion, we need this single belt survey (it was not planned at the start of this ticket).

**Comment by bob5ec** [comment]
Uuuf so many questions... And the only two I really care about are missing:
1. How much effort in hours was activity x for the team?
2. How does activity x impact risk reduction (measured in high impact vulnerabilities found and fixed in this activity)

PLEASE: Prioritize all these (interesting) question according to the value of the answers for US. Meaning: Who cares about the size of the company that uses the belts. We DO care about Aufwand and Nutzen.

**Comment by StefanDziwok** [comment]
Thanks for the input. In my opinion, your questions are relevant but not the only ones. 

My research goals of these surveys are:
1a. Is our security belt concept a good one for the teams that are using it?
1b. Is our security belt concept a good one for all software development teams of all companies?
3. Is each belt concept good - especially concerning difficulty, effort, and benefit. Moreover, does the management summary fit?
4. How much effort and benefit has each actvitiy?

My survey concept is as follows:
* Survey 1 (general concept) shall answer the goals 1a+b. Especially goal 1b requires several questions like company size, team size, and application kind to understand which teams / companies we are evaluating. Obviously, goal 1b cannot be answered with the teams that we have, but my goal is to already collect data now.
* Survey 2 (specific belt) shall answer goal 2.
* An extended survey 2 or a separate Survey 3 shall answer goal 3. 

Survey is only half-done. In our meeting on Wednesday, I want to discuss my research goals and whether an extended 2nd survey or a new 3rd survey 2 are required.

**Comment by StefanDziwok** [comment]
`And the only two I really care about are missing:
1. How much effort in hours was activity x for the team?
2. How does activity x impact risk reduction (measured in high impact vulnerabilities found and fixed in this activity)`

Both questions are currently adressed on the belt level and are additionally planned for the activity level. However, a survey is only partially useful for this as the participants have to know that they need to measure these metrics before they start a belt / an activity. Measuring afterwards only is in my opinion unprecise. Furthermore, I find it hard to allocate a vulnerability to a specific activity. 

Furthermore, for some acitivities, measuring the identified high impact vulnerabilities can be hard, e.g. [1][2][3]. Maybe, we need more metrics to measure the impact of such activities (and yes, [measuring security is hard](https://ieeexplore.ieee.org/document/5432146). 

[1] https://github.com/AppSecure-nrw/security-belts/blob/master/yellow/false-positive-treatment.md
[2] https://github.com/AppSecure-nrw/security-belts/blob/master/orange/creation-of-evil-user-stories.md
[3] https://github.com/AppSecure-nrw/security-belts/blob/master/orange/team-has-a-security-champion.md

**Comment by merschs** [comment]
Same small remarks in the current surveys:
[2021-04-01_SurveyMonkey_BeltConcept_cmt.pdf](https://github.com/AppSecure-nrw/security-belts/files/6270474/2021-04-01_SurveyMonkey_BeltConcept_cmt.pdf)
[2021-04-01_SurveyMonkey_SingleBelt_cmt.pdf](https://github.com/AppSecure-nrw/security-belts/files/6270475/2021-04-01_SurveyMonkey_SingleBelt_cmt.pdf)

Apart from that, I think it is a good idea to have a short quick survey for every activity. As that would help to minimize the necessary questions and get feedback when it is still fresh in mind. I would propose to link to the survey from within each activity in that case. Downside is that the pseudonym usage becomes even more important. I would argue that we should make the answer mandatory and give in the description a pseudonym they can use if they don't want to participate, e.g. "Anon"

**Comment by StefanDziwok** [comment]
We create a third survey and will see which surveys the team use.
